import { TeamInfo } from './types';

export const nflTeams: TeamInfo[] = [
    {
      code: "ARI",
      name: "Cardinals",
      city: "Arizona",
      primaryColor: "#97233F",
      secondaryColor: "#FFB612",
      record: "4-13",
      recentForm: "L W L L W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/ARI",
    },
    {
      code: "ATL",
      name: "Falcons",
      city: "Atlanta",
      primaryColor: "#A71930",
      secondaryColor: "#000000",
      record: "7-10",
      recentForm: "L W L L W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/ATL",
    },
    {
      code: "BAL",
      name: "Ravens",
      city: "Baltimore",
      primaryColor: "#241773",
      secondaryColor: "#9E7C0C",
      record: "13-4",
      recentForm: "W W W W L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/BAL",
    },
    {
      code: "BUF",
      name: "Bills",
      city: "Buffalo",
      primaryColor: "#00338D",
      secondaryColor: "#C60C30",
      record: "11-6",
      recentForm: "W W W W W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/BUF",
    },
    {
      code: "CAR",
      name: "Panthers",
      city: "Carolina",
      primaryColor: "#0085CA",
      secondaryColor: "#101820",
      record: "2-15",
      recentForm: "L L L L W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/CAR",
    },
    {
      code: "CHI",
      name: "Bears",
      city: "Chicago",
      primaryColor: "#0B162A",
      secondaryColor: "#C83803",
      record: "7-10",
      recentForm: "W L W L W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/CHI",
    },
    {
      code: "CIN",
      name: "Bengals",
      city: "Cincinnati",
      primaryColor: "#FB4F14",
      secondaryColor: "#000000",
      record: "9-8",
      recentForm: "W W L W W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/CIN",
    },
    {
      code: "CLE",
      name: "Browns",
      city: "Cleveland",
      primaryColor: "#311D00",
      secondaryColor: "#FF3C00",
      record: "11-6",
      recentForm: "W W W W L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/CLE",
    },
    {
      code: "DAL",
      name: "Cowboys",
      city: "Dallas",
      primaryColor: "#041E42",
      secondaryColor: "#869397",
      record: "12-5",
      recentForm: "W W W L W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/DAL",
    },
    {
      code: "DEN",
      name: "Broncos",
      city: "Denver",
      primaryColor: "#002244",
      secondaryColor: "#FB4F14",
      record: "8-9",
      recentForm: "L L W W L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/DEN",
    },
    {
      code: "DET",
      name: "Lions",
      city: "Detroit",
      primaryColor: "#0076B6",
      secondaryColor: "#B0B7BC",
      record: "12-5",
      recentForm: "W W W L W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/DET",
    },
    {
      code: "GB",
      name: "Packers",
      city: "Green Bay",
      primaryColor: "#203731",
      secondaryColor: "#FFB612",
      record: "9-8",
      recentForm: "W W W L W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/GB",
    },
    {
      code: "HOU",
      name: "Texans",
      city: "Houston",
      primaryColor: "#03202F",
      secondaryColor: "#A71930",
      record: "10-7",
      recentForm: "W W L W W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/HOU",
    },
    {
      code: "IND",
      name: "Colts",
      city: "Indianapolis",
      primaryColor: "#002C5F",
      secondaryColor: "#A2AAAD",
      record: "9-8",
      recentForm: "W L W W L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/IND",
    },
    {
      code: "JAX",
      name: "Jaguars",
      city: "Jacksonville",
      primaryColor: "#006778",
      secondaryColor: "#D7A22A",
      record: "9-8",
      recentForm: "L L L W W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/JAX",
    },
    {
      code: "KC",
      name: "Chiefs",
      city: "Kansas City",
      primaryColor: "#E31837",
      secondaryColor: "#FFB612",
      record: "11-6",
      recentForm: "W W L W W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/KC",
    },
    {
      code: "LV",
      name: "Raiders",
      city: "Las Vegas",
      primaryColor: "#000000",
      secondaryColor: "#A5ACAF",
      record: "8-9",
      recentForm: "W W L W L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/LV",
    },
    {
      code: "LAC",
      name: "Chargers",
      city: "Los Angeles",
      primaryColor: "#0080C6",
      secondaryColor: "#FFC20E",
      record: "5-12",
      recentForm: "L L L L W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/LAC",
    },
    {
      code: "LAR",
      name: "Rams",
      city: "Los Angeles",
      primaryColor: "#003594",
      secondaryColor: "#FFA300",
      record: "10-7",
      recentForm: "W W W W L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/LA",
    },
    {
      code: "MIA",
      name: "Dolphins",
      city: "Miami",
      primaryColor: "#008E97",
      secondaryColor: "#F58220",
      record: "11-6",
      recentForm: "L W L W W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/MIA",
    },
    {
      code: "MIN",
      name: "Vikings",
      city: "Minnesota",
      primaryColor: "#4F2683",
      secondaryColor: "#FFC62F",
      record: "7-10",
      recentForm: "L L L W L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/MIN",
    },
    {
      code: "NE",
      name: "Patriots",
      city: "New England",
      primaryColor: "#002244",
      secondaryColor: "#C60C30",
      record: "4-13",
      recentForm: "L L W L L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/NE",
    },
    {
      code: "NO",
      name: "Saints",
      city: "New Orleans",
      primaryColor: "#D3BC8D",
      secondaryColor: "#101820",
      record: "9-8",
      recentForm: "W W W L W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/NO",
    },
    {
      code: "NYG",
      name: "Giants",
      city: "New York",
      primaryColor: "#0B2265",
      secondaryColor: "#A71930",
      record: "6-11",
      recentForm: "W W L W L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/NYG",
    },
    {
      code: "NYJ",
      name: "Jets",
      city: "New York",
      primaryColor: "#125740",
      secondaryColor: "#000000",
      record: "7-10",
      recentForm: "W L W L L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/NYJ",
    },
    {
      code: "PHI",
      name: "Eagles",
      city: "Philadelphia",
      primaryColor: "#004C54",
      secondaryColor: "#A5ACAF",
      record: "11-6",
      recentForm: "L L L L W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/PHI",
    },
    {
      code: "PIT",
      name: "Steelers",
      city: "Pittsburgh",
      primaryColor: "#FFB612",
      secondaryColor: "#101820",
      record: "10-7",
      recentForm: "W W W W L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/PIT",
    },
    {
      code: "SF",
      name: "49ers",
      city: "San Francisco",
      primaryColor: "#AA0000",
      secondaryColor: "#B3995D",
      record: "12-5",
      recentForm: "W W L W W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/SF",
    },
    {
      code: "SEA",
      name: "Seahawks",
      city: "Seattle",
      primaryColor: "#002244",
      secondaryColor: "#69BE28",
      record: "9-8",
      recentForm: "W L W W L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/SEA",
    },
    {
      code: "TB",
      name: "Buccaneers",
      city: "Tampa Bay",
      primaryColor: "#D50A0A",
      secondaryColor: "#FF7900",
      record: "9-8",
      recentForm: "W W L W L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/TB",
    },
    {
      code: "TEN",
      name: "Titans",
      city: "Tennessee",
      primaryColor: "#0C2340",
      secondaryColor: "#4B92DB",
      record: "6-11",
      recentForm: "W W L L W",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/TEN",
    },
    {
      code: "WAS",
      name: "Commanders",
      city: "Washington",
      primaryColor: "#5A1414",
      secondaryColor: "#FFB612",
      record: "4-13",
      recentForm: "L L L L L",
      logo: "https://static.www.nfl.com/t_q-best/league/api/clubs/logos/WAS",
    },
  ];
